### PR TITLE
fix(LocalStorage): LocalVolumeConvert state transition error

### LINKED ISSUE #1216: LocalStorage: state transition error
A state transition bug was found in Localstorage. It occurs in volumeConvertStart method in volume_convert_task_worker.go file.Thinking a scenario, some volume attribute .Spec.ReplicaNumber was updated successfully in cluster, and shift the LocalVolumeConvert State from Submitted to InProgress, but some  volume attribute .Spec.ReplicaNumber was updated with failure because of network flipping，and finally the LocalVolumeConvert state would be updated to InProgress without retry.It will cause the LocalVolumeConvert resource runs in a dead loop in the volumeConvertInProgress method because some volume replicaNumber without updating.

### PR DESCRIPTION
**Pull request by hikariwo**
#### What this PR does / why we need it:
fix #1216 
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

File: pkg/local-storage/member/controller/volume_convert_task_worker.go [hunk 1]
```diff
@@ -185,15 +185,14 @@ func (m *manager) volumeConvertStart(convert *apisv1alpha1.LocalVolumeConvert) e
 			for _, vol := range volList.Items {
 				if vol.Spec.VolumeGroup == lvg.Name {
 					if vol.Spec.ReplicaNumber == convert.Spec.ReplicaNumber {
-						convert.Status.State = apisv1alpha1.OperationStateInProgress
-						m.apiClient.Status().Update(ctx, convert)
+						continue
```
Comment (SSmallMonster) [inline pkg/local-storage/member/controller/volume_convert_task_worker.go:188]: `continue` is necessary, but the status should also be updated to `InProgress`

**Review by SSmallMonster — CHANGES_REQUESTED** [review]

File: pkg/local-storage/member/controller/volume_convert_task_worker.go (hunk 1 above)
Comment (hikariwo) [reply pkg/local-storage/member/controller/volume_convert_task_worker.go:188]: The status will be updated to InProgress at line 203, after all lv.spec.replicaNumber was updating.

**Comment by SSmallMonster** [comment]
lgtm

**Review by SSmallMonster — APPROVED** [review]
